export const swrKeys = {
  GET_ORGANIZATION_MEMBERS: 'GET_ORGANIZATION_MEMBERS',
  GET_ORGANIZATION_INVITES: 'GET_ORGANIZATION_INVITES',

  DELETE_ORGANIZATION_MEMBER: 'DELETE_ORGANIZATION_MEMBER',
  DELETE_ORGANIZATION_INVITE: 'DELETE_ORGANIZATION_INVITE',
}
